/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CreateInvoiceRouteImport } from './routes/create-invoice'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MarketRouteImport } from './routes/market'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuctionIdRouteImport } from './routes/auction.$id'
import { Route as DashboardBusinessRouteImport } from './routes/dashboard.business'
import { Route as DashboardBuyerRouteImport } from './routes/dashboard.buyer'
import { Route as DashboardLenderRouteImport } from './routes/dashboard.lender'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as ApiArcRpcRouteImport } from './routes/api.arc.rpc'
import { Route as ApiCircleChallengeRouteImport } from './routes/api.circle.challenge'
import { Route as ApiCircleWalletRouteImport } from './routes/api.circle.wallet'
import { Route as ApiCircleWebhookRouteImport } from './routes/api.circle.webhook'
import { Route as ApiCircleChallengeIdRouteImport } from './routes/api.circle.challenge.$id'
import { Route as ApiCircleSocialConfigRouteImport } from './routes/api.circle.social.config'
import { Route as ApiCircleSocialDeviceTokenRouteImport } from './routes/api.circle.social.device-token'
import { Route as ApiCircleSocialInitializeRouteImport } from './routes/api.circle.social.initialize'
import { Route as ApiCircleTransactionIdRouteImport } from './routes/api.circle.transaction.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateInvoiceRoute = CreateInvoiceRouteImport.update({
  id: '/create-invoice',
  path: '/create-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionIdRoute = AuctionIdRouteImport.update({
  id: '/auction/$id',
  path: '/auction/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBusinessRoute = DashboardBusinessRouteImport.update({
  id: '/dashboard/business',
  path: '/dashboard/business',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuyerRoute = DashboardBuyerRouteImport.update({
  id: '/dashboard/buyer',
  path: '/dashboard/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLenderRoute = DashboardLenderRouteImport.update({
  id: '/dashboard/lender',
  path: '/dashboard/lender',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArcRpcRoute = ApiArcRpcRouteImport.update({
  id: '/api/arc/rpc',
  path: '/api/arc/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCircleChallengeRoute = ApiCircleChallengeRouteImport.update({
  id: '/api/circle/challenge',
  path: '/api/circle/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCircleWalletRoute = ApiCircleWalletRouteImport.update({
  id: '/api/circle/wallet',
  path: '/api/circle/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCircleWebhookRoute = ApiCircleWebhookRouteImport.update({
  id: '/api/circle/webhook',
  path: '/api/circle/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCircleChallengeIdRoute = ApiCircleChallengeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCircleChallengeRoute,
} as any)
const ApiCircleSocialConfigRoute = ApiCircleSocialConfigRouteImport.update({
  id: '/api/circle/social/config',
  path: '/api/circle/social/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCircleSocialDeviceTokenRoute =
  ApiCircleSocialDeviceTokenRouteImport.update({
    id: '/api/circle/social/device-token',
    path: '/api/circle/social/device-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCircleSocialInitializeRoute =
  ApiCircleSocialInitializeRouteImport.update({
    id: '/api/circle/social/initialize',
    path: '/api/circle/social/initialize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCircleTransactionIdRoute = ApiCircleTransactionIdRouteImport.update({
  id: '/api/circle/transaction/$id',
  path: '/api/circle/transaction/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/connect': typeof ConnectRoute
  '/create-invoice': typeof CreateInvoiceRoute
  '/how-it-works': typeof HowItWorksRoute
  '/market': typeof MarketRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auction/$id': typeof AuctionIdRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/lender': typeof DashboardLenderRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/api/arc/rpc': typeof ApiArcRpcRoute
  '/api/circle/challenge': typeof ApiCircleChallengeRouteWithChildren
  '/api/circle/wallet': typeof ApiCircleWalletRoute
  '/api/circle/webhook': typeof ApiCircleWebhookRoute
  '/api/circle/challenge/$id': typeof ApiCircleChallengeIdRoute
  '/api/circle/social/config': typeof ApiCircleSocialConfigRoute
  '/api/circle/social/device-token': typeof ApiCircleSocialDeviceTokenRoute
  '/api/circle/social/initialize': typeof ApiCircleSocialInitializeRoute
  '/api/circle/transaction/$id': typeof ApiCircleTransactionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/connect': typeof ConnectRoute
  '/create-invoice': typeof CreateInvoiceRoute
  '/how-it-works': typeof HowItWorksRoute
  '/market': typeof MarketRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auction/$id': typeof AuctionIdRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/lender': typeof DashboardLenderRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/api/arc/rpc': typeof ApiArcRpcRoute
  '/api/circle/challenge': typeof ApiCircleChallengeRouteWithChildren
  '/api/circle/wallet': typeof ApiCircleWalletRoute
  '/api/circle/webhook': typeof ApiCircleWebhookRoute
  '/api/circle/challenge/$id': typeof ApiCircleChallengeIdRoute
  '/api/circle/social/config': typeof ApiCircleSocialConfigRoute
  '/api/circle/social/device-token': typeof ApiCircleSocialDeviceTokenRoute
  '/api/circle/social/initialize': typeof ApiCircleSocialInitializeRoute
  '/api/circle/transaction/$id': typeof ApiCircleTransactionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/connect': typeof ConnectRoute
  '/create-invoice': typeof CreateInvoiceRoute
  '/how-it-works': typeof HowItWorksRoute
  '/market': typeof MarketRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auction/$id': typeof AuctionIdRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/lender': typeof DashboardLenderRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/api/arc/rpc': typeof ApiArcRpcRoute
  '/api/circle/challenge': typeof ApiCircleChallengeRouteWithChildren
  '/api/circle/wallet': typeof ApiCircleWalletRoute
  '/api/circle/webhook': typeof ApiCircleWebhookRoute
  '/api/circle/challenge/$id': typeof ApiCircleChallengeIdRoute
  '/api/circle/social/config': typeof ApiCircleSocialConfigRoute
  '/api/circle/social/device-token': typeof ApiCircleSocialDeviceTokenRoute
  '/api/circle/social/initialize': typeof ApiCircleSocialInitializeRoute
  '/api/circle/transaction/$id': typeof ApiCircleTransactionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/connect'
    | '/create-invoice'
    | '/how-it-works'
    | '/market'
    | '/portfolio'
    | '/settings'
    | '/sitemap.xml'
    | '/auction/$id'
    | '/dashboard/business'
    | '/dashboard/buyer'
    | '/dashboard/lender'
    | '/invoice/$id'
    | '/api/arc/rpc'
    | '/api/circle/challenge'
    | '/api/circle/wallet'
    | '/api/circle/webhook'
    | '/api/circle/challenge/$id'
    | '/api/circle/social/config'
    | '/api/circle/social/device-token'
    | '/api/circle/social/initialize'
    | '/api/circle/transaction/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/connect'
    | '/create-invoice'
    | '/how-it-works'
    | '/market'
    | '/portfolio'
    | '/settings'
    | '/sitemap.xml'
    | '/auction/$id'
    | '/dashboard/business'
    | '/dashboard/buyer'
    | '/dashboard/lender'
    | '/invoice/$id'
    | '/api/arc/rpc'
    | '/api/circle/challenge'
    | '/api/circle/wallet'
    | '/api/circle/webhook'
    | '/api/circle/challenge/$id'
    | '/api/circle/social/config'
    | '/api/circle/social/device-token'
    | '/api/circle/social/initialize'
    | '/api/circle/transaction/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/connect'
    | '/create-invoice'
    | '/how-it-works'
    | '/market'
    | '/portfolio'
    | '/settings'
    | '/sitemap.xml'
    | '/auction/$id'
    | '/dashboard/business'
    | '/dashboard/buyer'
    | '/dashboard/lender'
    | '/invoice/$id'
    | '/api/arc/rpc'
    | '/api/circle/challenge'
    | '/api/circle/wallet'
    | '/api/circle/webhook'
    | '/api/circle/challenge/$id'
    | '/api/circle/social/config'
    | '/api/circle/social/device-token'
    | '/api/circle/social/initialize'
    | '/api/circle/transaction/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ConnectRoute: typeof ConnectRoute
  CreateInvoiceRoute: typeof CreateInvoiceRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MarketRoute: typeof MarketRoute
  PortfolioRoute: typeof PortfolioRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuctionIdRoute: typeof AuctionIdRoute
  DashboardBusinessRoute: typeof DashboardBusinessRoute
  DashboardBuyerRoute: typeof DashboardBuyerRoute
  DashboardLenderRoute: typeof DashboardLenderRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  ApiArcRpcRoute: typeof ApiArcRpcRoute
  ApiCircleChallengeRoute: typeof ApiCircleChallengeRouteWithChildren
  ApiCircleWalletRoute: typeof ApiCircleWalletRoute
  ApiCircleWebhookRoute: typeof ApiCircleWebhookRoute
  ApiCircleSocialConfigRoute: typeof ApiCircleSocialConfigRoute
  ApiCircleSocialDeviceTokenRoute: typeof ApiCircleSocialDeviceTokenRoute
  ApiCircleSocialInitializeRoute: typeof ApiCircleSocialInitializeRoute
  ApiCircleTransactionIdRoute: typeof ApiCircleTransactionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-invoice': {
      id: '/create-invoice'
      path: '/create-invoice'
      fullPath: '/create-invoice'
      preLoaderRoute: typeof CreateInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/$id': {
      id: '/auction/$id'
      path: '/auction/$id'
      fullPath: '/auction/$id'
      preLoaderRoute: typeof AuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/business': {
      id: '/dashboard/business'
      path: '/dashboard/business'
      fullPath: '/dashboard/business'
      preLoaderRoute: typeof DashboardBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/dashboard/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/lender': {
      id: '/dashboard/lender'
      path: '/dashboard/lender'
      fullPath: '/dashboard/lender'
      preLoaderRoute: typeof DashboardLenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arc/rpc': {
      id: '/api/arc/rpc'
      path: '/api/arc/rpc'
      fullPath: '/api/arc/rpc'
      preLoaderRoute: typeof ApiArcRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/circle/challenge': {
      id: '/api/circle/challenge'
      path: '/api/circle/challenge'
      fullPath: '/api/circle/challenge'
      preLoaderRoute: typeof ApiCircleChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/circle/wallet': {
      id: '/api/circle/wallet'
      path: '/api/circle/wallet'
      fullPath: '/api/circle/wallet'
      preLoaderRoute: typeof ApiCircleWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/circle/webhook': {
      id: '/api/circle/webhook'
      path: '/api/circle/webhook'
      fullPath: '/api/circle/webhook'
      preLoaderRoute: typeof ApiCircleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/circle/challenge/$id': {
      id: '/api/circle/challenge/$id'
      path: '/$id'
      fullPath: '/api/circle/challenge/$id'
      preLoaderRoute: typeof ApiCircleChallengeIdRouteImport
      parentRoute: typeof ApiCircleChallengeRoute
    }
    '/api/circle/social/config': {
      id: '/api/circle/social/config'
      path: '/api/circle/social/config'
      fullPath: '/api/circle/social/config'
      preLoaderRoute: typeof ApiCircleSocialConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/circle/social/device-token': {
      id: '/api/circle/social/device-token'
      path: '/api/circle/social/device-token'
      fullPath: '/api/circle/social/device-token'
      preLoaderRoute: typeof ApiCircleSocialDeviceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/circle/social/initialize': {
      id: '/api/circle/social/initialize'
      path: '/api/circle/social/initialize'
      fullPath: '/api/circle/social/initialize'
      preLoaderRoute: typeof ApiCircleSocialInitializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/circle/transaction/$id': {
      id: '/api/circle/transaction/$id'
      path: '/api/circle/transaction/$id'
      fullPath: '/api/circle/transaction/$id'
      preLoaderRoute: typeof ApiCircleTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiCircleChallengeRouteChildren {
  ApiCircleChallengeIdRoute: typeof ApiCircleChallengeIdRoute
}

const ApiCircleChallengeRouteChildren: ApiCircleChallengeRouteChildren = {
  ApiCircleChallengeIdRoute: ApiCircleChallengeIdRoute,
}

const ApiCircleChallengeRouteWithChildren =
  ApiCircleChallengeRoute._addFileChildren(ApiCircleChallengeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ConnectRoute: ConnectRoute,
  CreateInvoiceRoute: CreateInvoiceRoute,
  HowItWorksRoute: HowItWorksRoute,
  MarketRoute: MarketRoute,
  PortfolioRoute: PortfolioRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuctionIdRoute: AuctionIdRoute,
  DashboardBusinessRoute: DashboardBusinessRoute,
  DashboardBuyerRoute: DashboardBuyerRoute,
  DashboardLenderRoute: DashboardLenderRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  ApiArcRpcRoute: ApiArcRpcRoute,
  ApiCircleChallengeRoute: ApiCircleChallengeRouteWithChildren,
  ApiCircleWalletRoute: ApiCircleWalletRoute,
  ApiCircleWebhookRoute: ApiCircleWebhookRoute,
  ApiCircleSocialConfigRoute: ApiCircleSocialConfigRoute,
  ApiCircleSocialDeviceTokenRoute: ApiCircleSocialDeviceTokenRoute,
  ApiCircleSocialInitializeRoute: ApiCircleSocialInitializeRoute,
  ApiCircleTransactionIdRoute: ApiCircleTransactionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
